[package]
name = "stateless-block-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
hex = "0.4"
eth-types = { git = "https://github.com/scroll-tech/zkevm-circuits", features = ["scroll"], branch = "refactor/mpt-witness" }
mpt-zktrie = { git = "https://github.com/scroll-tech/zkevm-circuits", branch = "refactor/mpt-witness" }
revm = { git = "https://github.com/scroll-tech/revm", default-features=false, features = ["scroll-default-handler", "std"], rev = "e1e8f7a" } # v35
zktrie = { git = "https://github.com/scroll-tech/zktrie.git", branch = "main", features= ["rs_zktrie"] }

# binary dependencies
anyhow = { version = "1.0", optional = true }
clap = { version = "4", features = ["derive"], optional = true }
env_logger = { version = "0.9", optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[[bin]]
name = "trace-verifier"
required-features = ["bin-deps"]

[features]
bin-deps = ["anyhow", "clap", "env_logger", "serde_json", "serde"]

[patch.crates-io]
ethers-core = { git = "https://github.com/scroll-tech/ethers-rs.git", branch = "v2.0.7" }
ethers-signers  = { git = "https://github.com/scroll-tech/ethers-rs.git", branch = "v2.0.7" }
halo2curves = { git = "https://github.com/scroll-tech/halo2curves", branch = "v0.1.0" }

[patch."https://github.com/privacy-scaling-explorations/bls12_381"]
bls12_381 = { git = "https://github.com/scroll-tech/bls12_381", branch = "feat/impl_scalar_field" }
